debug: true
secret: changethissecret
locale_fallback: en

doctrine:
    dbal:
        driver:   pdo_mysql
        port:     3306
        host:     localhost
        dbname:
        user:
        password:
        charset:  UTF8